// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "link":return img`
........................
......ffff..............
....fff77fff............
...fff7777fff...........
..fffeeeeeefff..........
..ffe777777eef..........
..fe7ffffff7ef..........
..ffffeeeeffff..........
.ffefb6446bfeff.........
.fee416dd614eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f7777edde...........
fcf.ff7fffee............
.ff.f7ffdf7f............
....fff5dfff............
.....fddfff.............
....fddf.f..............
....fdf...f.............
....fff..f..............
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
