scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleBlueCrystal, function (sprite, location) {
    game.gameOver(true)
})
music.play(music.stringPlayable("C D C F A G E C5 ", 121), music.PlaybackMode.LoopingInBackground)
game.splash("press \"A\"too play")
let alan = sprites.create(assets.image`link`, SpriteKind.Player)
controller.moveSprite(alan)
tiles.setCurrentTilemap(tilemap`nivel1`)
scene.cameraFollowSprite(alan)
effects.starField.startScreenEffect()
tiles.placeOnRandomTile(alan, sprites.dungeon.collectibleRedCrystal)
let projectile = sprites.createProjectileFromSprite(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .....ffff111111bf.......
    ....fc111cdb1bdfff......
    ....f1b1bcbfbfc111cf....
    ....fbfbfbffff1b1b1f....
    .........fffffffbfbf....
    ..........fffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, alan, 50, 50)
info.startCountdown(60)
